version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "1170:1170"
    depends_on:
      - auth
      - classrooms
      - event-bus
      - post
      - mongo
    networks:
      - app-network

  auth:
    build:
      context: ./Auth
      dockerfile: Dockerfile
    ports:
      - "3001:13170"
    networks:
      - app-network

  classrooms:
    build:
      context: ./Classrooms
      dockerfile: Dockerfile
    ports:
      - "3002:23170"
    networks:
      - app-network

  event-bus:
    build:
      context: ./event-bus
      dockerfile: Dockerfile
    ports:
      - "3003:33170"
    networks:
      - app-network

  post:
    build:
      context: ./POST
      dockerfile: Dockerfile
    ports:
      - "3004:43170"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
