apiVersion: apps/v1
kind: Deployment
metadata:
  name: classrooms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classrooms
  template:
    metadata:
      labels:
        app: classrooms
    spec:
      containers:
      - name: client
        image: alicodes02/classrooms:latest
        ports:
        - containerPort: 23170
---
apiVersion: v1
kind: Service
metadata:
  name: classrooms-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 23170
  selector:
    app: classrooms
