apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: client
        image: alicodes02/event-bus:latest
        ports:
        - containerPort: 31370
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-service
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 31370
  selector:
    app: event-bus
